feat(input): add help/descriptor text
karnama/vueish pull request #516
Opened 2022-09-11 17:55 UTC by stubbo

![Screenshot 2022-09-11 at 18 55 16](https://user-images.githubusercontent.com/8171714/189542020-99a0c1b1-6f93-4702-ab80-fd1936440caa.png)

2022-09-11 17:55 UTC, stubbo commented
@fullstackfool

2022-09-12 16:15 UTC, nandi95 requested changes
🦦

2022-09-12 16:15 UTC, nandi95 commented on src/components/input/Demo.vue
> +        const helpSlot = ref('I\'m an input!');
One is enough here

2022-09-12 16:15 UTC, nandi95 commented on src/components/input/Demo.vue
> +        const helpSlot = ref('I\'m an input!');
Altough I realise no point of having v-models at all given the component isn't updated from the outside

2022-09-12 16:15 UTC, nandi95 commented on src/components/input/Demo.vue
> +                 help="Idiot proof message..."
use some nicer message, only because this is open source 😅

2022-09-12 16:15 UTC, nandi95 commented on src/components/input/UIInput.vue
> +            <div v-if="error || $slots.error || help || $slots.help">
you introduced a redundant `<div>` here. You can use `<template>` which is only a logical block and won't render anything.

2022-09-12 16:15 UTC, nandi95 commented on src/components/input/UIInput.vue
> +                <slot v-if="(help || $slots.help) && !error && !$slots.error" name="help">
this could be simplified by a `v-if=""` and `v-else-if=""`

2022-09-12 16:15 UTC, nandi95 commented on src/components/input/UIInput.vue
> +        help: {
Little comment here please like in the above props.

2022-09-12 16:15 UTC, nandi95 commented on src/components/input/UIInput.vue
> +                        {{ help }}
if we gonna have this, can you please implement the same for all other inputs too? Or at least the inputs which have the same box layout (textarea, select, file input)

2022-09-12 16:15 UTC, nandi95 commented on src/components/input/UIInput.vue
> +                        {{ help }}
Could you add testing please? You'll find other examples how a prop/slot like this is tested

2022-09-13 18:56 UTC, nandi95 requested changes
🦦

2022-09-13 18:56 UTC, nandi95 commented on src/components/input/UIInput.vue
> +        <UIExpandTransition :height-duration="100" :opacity-duration="200">
keep it default (as that's consistent with other inputs)

```suggestion
        <UIExpandTransition>
```

2022-09-13 18:56 UTC, nandi95 commented on src/components/input/UIInput.test.ts
> +    it('should display the only error text when both help and error are passed as prop', () => {
👍

2022-09-13 18:56 UTC, nandi95 commented on src/components/input/Demo.vue
> +                <span class="animate-pulse text-sm mt-1 text-color-muted">Descriptive message...</span>
no need for the pulse animation (bit distracting 😅), if you wanna sho it's custom just say `Slotted descriptive message...`

2022-09-13 18:56 UTC, nandi95 commented on src/components/input/UIInput.vue
> +            </template>
sorry to be a pain but what do you think about this?
```suggestion
            <div v-if="error || $slots.error || help || $slots.help">
                <UIFadeTransition>
                    <slot v-if="error || $slots.error" name="error">
                        <p class="ui-error-text">
                            {{ error }}
                        </p>
                    </slot>

                    <slot v-else-if="(help || $slots.help)" name="help">
                        <p class="ui-help-text">
                            {{ help }}
                        </p>
                    </slot>
                </UIFadeTransition>
            </div>
```
cc @fullstackfool

2022-09-13 20:41 UTC, nandi95 approved these changes
🦦

2022-09-13 20:48 UTC, merged